import type { Metadata } from "next";
import "./globals.css";
import VantaBackground from "./components/VantaBackground";

import { eros } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={` ${eros.variable} antialiased relative z-10`}>
        <VantaBackground>{children}</VantaBackground>
      </body>
    </html>
  );
}
